CREATE TABLE domain_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64) NOT NULL,
    label VARCHAR(128) NOT NULL,
    data_type VARCHAR(16) NOT NULL,
    display_order SMALLINT NOT NULL,
    required BOOLEAN DEFAULT TRUE NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    CONSTRAINT pk_domain_field PRIMARY KEY (id),
    CONSTRAINT uq_domain_field_name UNIQUE (name),
    CONSTRAINT ck_domain_field_data_type CHECK (data_type IN ('integer', 'string'))
);

CREATE TABLE domain_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    domain_field_id BIGINT NOT NULL,
    value VARCHAR(64) NOT NULL,
    label VARCHAR(128) NOT NULL,
    display_order SMALLINT NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    CONSTRAINT pk_domain_option PRIMARY KEY (id),
    CONSTRAINT fk_domain_option_domain_field
        FOREIGN KEY (domain_field_id)
        REFERENCES domain_field (id),
    CONSTRAINT uq_domain_option_field_value UNIQUE (domain_field_id, value)
);

CREATE INDEX ix_domain_option_field_active_order
ON domain_option (domain_field_id, active, display_order);

CREATE TABLE obesity_record (
    id UUID NOT NULL,
    idade SMALLINT NOT NULL,
    sexo_biologico SMALLINT NOT NULL,
    come_vegetaiis SMALLINT NOT NULL,
    refeicoes_diariamente SMALLINT NOT NULL,
    come_entre_refeicao VARCHAR(16) NOT NULL,
    litro_agua SMALLINT NOT NULL,
    frequencia_semanal_atvidade_fisica SMALLINT NOT NULL,
    horas_dispositivo_eletronico SMALLINT NOT NULL,
    consome_bebida_alcoolica VARCHAR(16) NOT NULL,
    historico_familiar VARCHAR(3) NOT NULL,
    alimentos_calorico VARCHAR(3) NOT NULL,
    monitora_calorias VARCHAR(3) NOT NULL,
    fuma VARCHAR(3) NOT NULL,
    meio_transporte VARCHAR(32) NOT NULL,
    obesity VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    CONSTRAINT pk_obesity_record PRIMARY KEY (id),

    CONSTRAINT ck_record_idade
        CHECK (idade BETWEEN 1 AND 120),

    CONSTRAINT ck_record_sexo
        CHECK (sexo_biologico IN (1, 2)),

    CONSTRAINT ck_record_vegetais
        CHECK (come_vegetaiis IN (1, 2, 3)),

    CONSTRAINT ck_record_refeicoes
        CHECK (refeicoes_diariamente IN (1, 2, 3, 4, 5)),

    CONSTRAINT ck_record_entre_refeicao
        CHECK (come_entre_refeicao IN ('no', 'somentimes', 'frequently', 'always')),

    CONSTRAINT ck_record_agua
        CHECK (litro_agua IN (1, 2, 3)),

    CONSTRAINT ck_record_atividade
        CHECK (frequencia_semanal_atvidade_fisica IN (0, 1, 2, 3, 4)),

    CONSTRAINT ck_record_dispositivo
        CHECK (horas_dispositivo_eletronico IN (0, 1, 2)),

    CONSTRAINT ck_record_alcool
        CHECK (consome_bebida_alcoolica IN ('no', 'somentimes', 'frequently', 'always')),

    CONSTRAINT ck_record_historico
        CHECK (historico_familiar IN ('yes', 'no')),

    CONSTRAINT ck_record_calorico
        CHECK (alimentos_calorico IN ('yes', 'no')),

    CONSTRAINT ck_record_monitora_calorias
        CHECK (monitora_calorias IN ('yes', 'no')),

    CONSTRAINT ck_record_fuma
        CHECK (fuma IN ('yes', 'no')),

    CONSTRAINT ck_record_transporte
        CHECK (meio_transporte IN (
            'automobile',
            'motorbike',
            'bike',
            'public_transportation',
            'walking'
        )),

    CONSTRAINT ck_record_obesity
        CHECK (obesity IN (
            'Insufficient_Weight',
            'Normal_Weight',
            'Overweight_Level_I',
            'Overweight_Level_II',
            'Obesity_Type_I',
            'Obesity_Type_II',
            'Obesity_Type_III'
        ))
);

CREATE INDEX ix_obesity_record_created_at
ON obesity_record (created_at);